### ISSUE TITLE
Crash by editing scenario

### ISSUE THREAD

**Issue by fredsch** [calaos/calaos_base#101]
When you try to edit a scenario and want to add a break or add an ending step, the UI crash and  the changes aren’t saved.
![20150305_115557](https://cloud.githubusercontent.com/assets/9051112/6503624/ff9b0afa-c32e-11e4-976c-424481aeb8f9.jpg)

**Comment by raoulh** [comment]
What version do you have?

**Comment by fredsch** [comment]
Version 2.0.0 Stable on an Intel Nuc
