### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by tonyGit1** [calaos/calaos_base#111]
make[4]: quittant le répertoire « /home/tony/calaos_base/src/bin/calaos_server »
Making all in calaos_home
make[4]: entrant dans le répertoire « /home/tony/calaos_base/src/bin/calaos_home »
  CXX      ApplicationMain.o
ApplicationMain.cpp: In constructor ‘ApplicationMain::ApplicationMain(int, char**)’:
ApplicationMain.cpp:124:58: error: ‘elm_config_item_select_on_focus_disabled_set’ was not declared in this scope
         elm_config_item_select_on_focus_disabled_set(true);
                                                          ^

**Comment by raoulh** [comment]
You need at least efl 1.14.0 now
