### ISSUE TITLE
Electric shutter problem

### ISSUE THREAD

**Issue by jperroncel** [calaos/calaos_base#114]
Il semble qu'il y ai une inversion sur la gestion des volets roulants sur l'interface tactile :
- lorsque l'on utilise la commande "down" pour les volets le système indique que les volets sont ouverts
- lorsque l'on utilise la commande "up" le système indique qu'ils sont fermés
Ce fonctionnent est constaté sur :
- les volets "intelligents"
- les volets à impulsions

**Comment by naguirre** [comment]
Could you please re-open this issue and add comments in english ?
