### ISSUE TITLE
Something wrong in function （void MySensorsOutputAnalog::set_value_real(double val)）

### ISSUE THREAD

**Issue by xuxianyin5490** [calaos/calaos_base#118]
string nodeId = get_param("node_id_down");
    string sensorId = get_param("sensor_id_down");
maybe：
    string nodeId = get_param("node_id");
    string sensorId = get_param("sensor_id");

**Comment by raoulh** [comment]
You are right, fixed in e799f41598812d75c996eb61329b661f7e7336fd
thanks for reporting

**Comment by xuxianyin5490** [comment]
you are welcome!
