### ISSUE TITLE
Something wrong in function （bool OutputAnalog::set_value(double val)）

### ISSUE THREAD

**Issue by xuxianyin5490** [calaos/calaos_base#119]
the val value is right，but the v value is wrong（only have two value 0 or 65535）

**Comment by raoulh** [comment]
Could you be more precise? Add some more information for this bug?

**Comment by raoulh** [comment]
I fixed something related to your bug in master. Please try again and reopen the bug if needed. thanks

**Comment by xuxianyin5490** [comment]
ok

**Comment by xuxianyin5490** [comment]
It is right now，think you。
