### ISSUE TITLE
MySensors: serial and tcp can not use together 

### ISSUE THREAD

**Issue by xuxianyin5490** [calaos/calaos_base#127]
Hi，
    In MySensors module，when i controller my sensor use serial and tcp.  the TCP is ok ,but serial can not work.
only use serial is ok.

io.xml
<?xml version="1.0" encoding="UTF-8"?>
<calaos:ioconfig xmlns:calaos="http://www.calaos.fr">
    <calaos:home>
        <calaos:room name="4路" type="salon" hits="0">
            <calaos:input enabled="true" gateway="tcp" gui_type="switch" host="192.168.1.27" id="io_0" io_type="input" name="开关" node_id="1" port="8888" sensor_id="123456" type="MySensorsInputSwitch" visible="false"/>
            <calaos:input enabled="true" gateway="serial" gui_type="switch" id="io_2" io_type="input" name="开关_串口" node_id="1" port="/dev/ttyUSB0" sensor_id="12345" type="MySensorsInputSwitch" visible="false"/>
            <calaos:input id="io_4" io_type="input" name="teleinfo" port="/dev/ttyUSB0" type="TeleinfoInputAnalog"/>
            <calaos:output enabled="true" gateway="tcp" gui_type="light" host="192.168.1.27" id="io_1" io_type="output" name="灯" node_id="2" port="8888" sensor_id="123456" type="MySensorsOutputLight" visible="true"/>
            <calaos:output enabled="true" gateway="serial" gui_type="light" id="io_3" io_type="output" name="灯_串口" node_id="2" port="/dev/ttyUSB0" sensor_id="12345" type="MySensorsOutputLight" visible="true"/>
        </calaos:room>
    </calaos:home>
</calaos:ioconfig>

rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<calaos:rules xmlns:calaos="http://www.calaos.fr">
    <calaos:rule name="开关" type="4路">
        <calaos:condition type="standard" trigger="true">
            <calaos:input id="io_0" oper="==" val="changed"/>
        </calaos:condition>
        <calaos:action type="standard">
            <calaos:output id="io_1" val="toggle"/>
        </calaos:action>
    </calaos:rule>
</calaos:rules>

**Comment by naguirre** [comment]
ah yes you're right, currently only one controller at a time is supported.

**Comment by xuxianyin5490** [comment]
OK, Thank you all the same.
