### ISSUE TITLE
Android app connect error

### ISSUE THREAD

**Issue by xuxianyin5490** [calaos/calaos_base#128]
Hi,
When android app connect to server.
Error reporting:
[CRI] network (HttpClient.cpp:151) Error sending data ! Closing connection.

**Comment by naguirre** [comment]
This error should have been fixed by latest Android App revision (3.0.5) Could you please confirm and close the issue if this error is resolved ? Thanks.

**Comment by tiramiseb** [comment]
Hi,

I had the same problem and I don't have the problem anymore. I guess it is solved

**Comment by xuxianyin5490** [comment]
Hi,
Do you mean calaos_mobile version is 3.0.5? But the last version is 3.0.2.

![20170212224048](https://cloud.githubusercontent.com/assets/8021773/22863031/58b4a338-f174-11e6-8ee7-2ceca59d0b02.png)

**Comment by naguirre** [comment]
Yes it's 3.0.5, but i didn't push the code ^^ It's ok now.

**Comment by xuxianyin5490** [comment]
ok,Think you.

**Comment by xuxianyin5490** [comment]
Hi,  

I update my  Android App revision (3.0.5), but the error is not resolved.
