### ISSUE TITLE
Internal compiler error

### ISSUE THREAD

**Issue by xuxianyin5490** [calaos/calaos_base#131]
Hi,
My gcc version is gcc version 5.4.0 20160609. when I build the new version (commit 1f67963), have a   Internal compiler error.
uvw/src/uvw/process.hpp: In instantiation of ‘uvw::ProcessHandle& uvw::ProcessHandle::stdio(uvw::StreamHandle<T, U>&, uvw::Flags<uvw::details::UVStdIOFlags>) [with T = uvw::PipeHandle; U = uv_pipe_s]’:
UrlDownloader.cpp:172:33:   required from here
uvw/src/uvw/process.hpp:235:49: internal compiler error: in tsubst_copy, at cp/pt.c:13217
         container.data.stream = get<uv_stream_t>(stream);
                                                 ^
Please submit a full bug report,
with preprocessed source if appropriate.
**# Do you have the error? 
What's your gcc version?**

**Comment by raoulh** [comment]
I personally use a more recent gcc. But it should work with 5.4.
What OS are you using? Is the gcc coming from your distro or you self built this one?
Could you try with an other compiler version?

**Comment by xuxianyin5490** [comment]
My Os is ubuntu 16.04  .The gcc is coming from my distro.  I cann't try with an other compiler version.

**Comment by raoulh** [comment]
Ok, I'm going to try on ubuntu then and see what happens.

**Comment by raoulh** [comment]
So after some trials, GCC 5.4.0 is not supported. GCC 5.4.1 works and it's available in debian stable.
Ubuntu seems to not thinks it's worth it updating their compiler.
So best is to update your distro, or your compiler.
Sorry, i don't have any other solution.

**Comment by xuxianyin5490** [comment]
Still thank you.

**Comment by raoulh** [comment]
Just found that you can install gcc 6 on ubuntu by using this ppa:
https://cogeeuk.wordpress.com/2016/10/28/gcc-6-and-g-6-on-ubuntu/

**Comment by raoulh** [comment]
Hi, I just pushed some workaround that would make calaos_base build without the internal compiler error.
Please try to see if it works on your side

**Comment by xuxianyin5490** [comment]
Hi,I will try it.Thanks very much.
