### ISSUE TITLE
WebInput path

### ISSUE THREAD

**Issue by AussieGreg** [calaos/calaos_base#132]
I use a WebInput / WebInputTemp to get values from a text file:
http://192.168.1.53/ds18b20.txt
Content => 12.75,12.25,8.75

Path 1/2/, returns 12.25 => correct
Path 1/3/, returns 0 => not correct

If i change the content to 12.75,12.25,8.75,   => 1/3/,  = 8.75 

=> The extraction is not working for the last value

**Comment by raoulh** [comment]
Works with git master
