### ISSUE TITLE
Add a way to determine which input(s) triggered a LUA script

### ISSUE THREAD

**Issue by mifrey00** [calaos/calaos_base#133]
Add a way to determine in a LUA script which input(s) triggered this script.  This would allow to execute different instructions depending on the input(s) that changed.

**Comment by raoulh** [comment]
Usage:

```lua
local trigger_id = calaos:getEnv("trigger_id")

print("Id that triggered: " .. trigger_id)

return false
```

**Comment by mifrey00** [comment]
Great!
