### ISSUE TITLE
HttpClient send corrupt data

### ISSUE THREAD

**Issue by FragJage** [calaos/calaos_base#135]
On calaos_server, the method HttpClient::sendToClient use c_str pointer from a local string to send data with write method of uvw. When libuv send data, the local string is free. For little string there is not problem, but on my server (ubuntu 14.04, cpu atom, 2 Go) files such as jquery.js or angular.js is send corrupted.

**Comment by raoulh** [comment]
Nice catch, will fix that,
thanks

**Comment by FragJage** [comment]
Very nice, it's ok on my server.
Thanks
