### ISSUE TITLE
calaos_mail doesn't send the body payload

### ISSUE THREAD

**Issue by StevenLeRoux** [calaos/calaos_base#148]
Testing the SMTPS email provider on the calaos image, I've send few emails that all arrive without any body payload. 

I still receive the emails, but as empty ones.

**Comment by raoulh** [comment]
What is you smtp config?
Did you try with calaos_mail command?

**Comment by StevenLeRoux** [comment]
SMTPS to smtp.gmail.com with TLS enabled.

SMTP is working since I've received emails : https://dl.plik.ovh/file/euJ6BQK0sBUT2mTh/tMgF49kRZxsiJsBQ/Screenshot%202020-03-16%20at%2012.00.33.png

I've tried with the example on the documentation and calaos_mail command

**Comment by raoulh** [comment]
Can you give the calaos_mail used please

**Comment by StevenLeRoux** [comment]
The one from this image : https://www.calaos.fr/download/experimental/calaos-os/intel-corei7-64/calaos-os-intel-corei7-64-v3.0-beta1-3-g0bd4448-2019-04-26.tar.xz

**Comment by raoulh** [comment]
Sorry I mean the full command you typed to test with calaos_mail

**Comment by StevenLeRoux** [comment]
Oh sorry :) 

It was something like : 

calaos_mail --source_email@domain.tld --to target_email@domain.tld --subject "calaos mail" --body "calaos test" --verbose

The NUC is behind a 4G access for now, so I don't have any remote access to give you the exact command from history

**Comment by raoulh** [comment]
```
--body <filename>
```
You should pass a filename with the body content, not the content itself
