### ISSUE TITLE
Add support for PING protocol

### ISSUE THREAD

**Issue by naguirre** [calaos/calaos_base#70]
Add PING Input in calaos_installer and calaos_installer. The goal is to give to the input the IPv4 or IPv6 address of an host, a frequency. Then calaos server ping this host at the frequency given. The input is true as long as the host answer the ping request, false otherwise

**Comment by raoulh** [comment]
fixed in https://github.com/calaos/calaos_base/commit/e2c893102793eb9a3dc600cb1d3bfc17d54ac4b8
