### ISSUE TITLE
Assumption of a bug in editing or restitution of scenarios calaos home.

### ISSUE THREAD

**Issue by bill3535** [calaos/calaos_base#93]
Otherwise level scenarios, creating the touch I see all my actions associated screen. By cons after recovery of calaos installer
![2015-01-14 16 38 27](https://cloud.githubusercontent.com/assets/10126882/5741604/76f0042e-9c0c-11e4-9fbb-ebfcc60d4f6b.jpg)
 and referred by it on the touch screen all my scenarios happening in --other scenario and I do yellow NO ACTION. But the scenarios work anyway.

**Comment by raoulh** [comment]
Bug in calaos_installer, fixed in https://github.com/calaos/calaos_installer/commit/af92f88fbf8f795c458fb0fd2722901183394ab4
