### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [calaos/calaos_base#95]
I would like to point out that identifiers like "[`_CalaosModuleApi`](https://github.com/calaos/calaos_base/blob/0e032a519adb4bd9ec4b64b1fc215f93c7349080/src/lib/CalaosModule.h#L63)" and "[`__daylen__`](https://github.com/calaos/calaos_base/blob/7a034e23b26d4e815e3ba986f19210620a20205d/src/lib/sunset.h#L126)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by raoulh** [comment]
If that cause you a problem, you can provide a pull request to fix it.
