### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [calaos/calaos_base#98]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/calaos/calaos_base/blob/969f0e5d2b9b4a26f1289b322cac8844dcfa43f5/configure.ac#L51 "Configuration checks")?

**Comment by raoulh** [comment]
fixed in https://github.com/calaos/calaos_base/commit/d3f95703794f21089b6a9fdb217e3913aeeceda6

**Comment by elfring** [comment]
How do you think about to add [a few details](https://github.com/calaos/calaos_base/blob/4fe4460a750598c6e19c866e7eebfd0c32677e11/configure.ac#L165 "Update candidate") for the function parameters "ACTION-IF-FOUND" and "ACTION-IF-NOT-FOUND"?
Would you like to look at comments from the added configuration script once more?

**Comment by naguirre** [comment]
Why not, patched welcome :-)

**Comment by elfring** [comment]
Further considerations:
* Does the POSIX thread interface belong to the mandatory dependencies for your software?
* How do you think about to pass [the function "AC_MSG_ERROR"](http://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Printing-Messages.html#index-AC_005fMSG_005fERROR-1229 "Program exit") for the parameter "ACTION-IF-NOT-FOUND"?
