### ISSUE TITLE
Protect against spurious wakeups

### ISSUE THREAD

**Issue by elfring** [calaos/calaos_base#99]
I have seen that [no loop is used around a call](https://github.com/calaos/calaos_base/blob/87e6ae32e79dcb5fc62cdd342d0aa5bf35878f25/src/bin/calaos_server/IO/Wago/WagoMap.cpp#L284 "Check WagoMap::ThreadProc") of the function "[condition_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html "wait on a condition")".
Would you like to reuse anything from my message on the topic "[spurious wakeup](http://groups.google.de/group/comp.programming.threads/msg/bb8299804652fdd7 "Discussion about handling of spurious wakeups")"?

**Comment by raoulh** [comment]
fixed
